"""Cloud training on Kaggle's free GPUs, driven entirely from nanolab.

`nanolab train --cloud <config>` pushes a script kernel that clones this
repo, trains with `--resume`, runs the held-out exam, and leaves
adapters + the db as kernel output. `nanolab cloud pull` downloads that
output and merges it into the local lab. The user never opens a notebook.

Requires a one-time Kaggle setup: phone-verified account + API token at
~/.kaggle/kaggle.json. Kaggle constraint worth knowing: kernel logs and
output become available when the run FINISHES — status is live, logs are
not.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

from . import db

REPO_URL = "https://github.com/khwahish1509/RLPost.git"
KERNEL_DIR = Path(".cache") / "kaggle-kernel"
OUTPUT_DIR = Path(".cache") / "kaggle-output"

# Environments that live in this repo (not on the Hub) install as editable
# packages instead of via `prime env install`.
LOCAL_ENV_DIRS = {
    "scribe-stream": "environments/scribe_stream",
    "pattern-gym": "environments/pattern_gym",
}


class CloudError(RuntimeError):
    pass


def _kaggle(args: list[str]) -> str:
    if not (Path.home() / ".kaggle" / "kaggle.json").exists():
        raise CloudError(
            "Kaggle API token missing. One-time setup: kaggle.com/settings → "
            "Create New Token → save as ~/.kaggle/kaggle.json (chmod 600). "
            "GPU kernels also need a phone-verified account."
        )
    proc = subprocess.run(["kaggle", *args], capture_output=True, text=True)
    if proc.returncode != 0:
        raise CloudError((proc.stderr or proc.stdout).strip()[-400:])
    return proc.stdout


def _username() -> str:
    return json.loads((Path.home() / ".kaggle" / "kaggle.json").read_text())["username"]


def kernel_slug(config_path: str | Path) -> str:
    stem = re.sub(r"[^a-z0-9-]+", "-", Path(config_path).stem.lower()).strip("-")
    return f"nanolab-train-{stem}"[:50]


def _config_env_id(config_path: str | Path) -> str:
    """The single [[env]].id declared by a training config (empty if unreadable)."""
    import tomllib

    try:
        data = tomllib.loads(Path(config_path).read_text())
    except (OSError, tomllib.TOMLDecodeError):
        return ""
    envs = data.get("env", [])
    return str(envs[0]["id"]) if envs and "id" in envs[0] else ""


def _env_install_cmd(env_id: str) -> str:
    """Shell command that makes `env_id` importable inside the kernel."""
    if env_id in LOCAL_ENV_DIRS:
        # in-repo environment (cloned with the repo) → editable install
        return f'sh(f"{{sys.executable}} -m pip install -q -e {LOCAL_ENV_DIRS[env_id]}")'
    return f'sh("prime env install {env_id} --with pip")'


def _exam_cmd(env_id: str) -> str:
    """The held-out exam to run after training, if one exists for this env.

    Only gsm8k has an in-kernel exam today; for every other env the verdict is
    produced locally after `nanolab cloud pull` (serve the adapter, re-eval).
    """
    if env_id == "primeintellect/gsm8k":
        return 'sh(f"{sys.executable} scripts/compare_adapter.py")'
    return f'print("no in-kernel exam for {env_id}; verdict runs locally after pull", flush=True)'


def build_kernel_script(config_path: str | Path) -> str:
    env_id = _config_env_id(config_path)
    return f'''"""nanolab cloud training kernel — generated by `nanolab train --cloud`."""
import os, subprocess, sys

def sh(cmd):
    print("$", cmd, flush=True)
    subprocess.run(cmd, shell=True, check=True)

sh("git clone --depth 1 {REPO_URL} nanolab")
os.chdir("nanolab")
sh(f"{{sys.executable}} -m pip install -q -e . peft prime")
# Kaggle image ships torchao 0.10, which fresh peft rejects on import;
# absent is fine, old is fatal — so remove it
sh(f"{{sys.executable}} -m pip uninstall -q -y torchao")
# env for {env_id!r}: Hub envs install via prime, in-repo envs as editable pkgs
{_env_install_cmd(env_id)}
sh(f"{{sys.executable}} -m nanolab.cli train {config_path} --resume")
{_exam_cmd(env_id)}
sh("zip -qr /kaggle/working/nanolab-artifacts.zip adapters results/nanolab.db")
print("CLOUD RUN COMPLETE", flush=True)
'''


def build_kernel_metadata(config_path: str | Path) -> dict:
    slug = kernel_slug(config_path)
    return {
        "id": f"{_username()}/{slug}",
        "title": slug,
        "code_file": "kernel_script.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": "true",
        "enable_gpu": "true",
        # T4 explicitly: Kaggle's default can assign a P100, whose Pascal
        # architecture modern PyTorch wheels no longer ship kernels for
        "machine_shape": "NvidiaTeslaT4",
        "enable_internet": "true",
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }


def push(config_path: str | Path) -> str:
    config = Path(config_path)
    if not config.is_file():
        raise CloudError(f"Config not found: {config}")
    KERNEL_DIR.mkdir(parents=True, exist_ok=True)
    meta = build_kernel_metadata(config)
    (KERNEL_DIR / "kernel-metadata.json").write_text(json.dumps(meta, indent=2))
    (KERNEL_DIR / "kernel_script.py").write_text(build_kernel_script(config))
    out = _kaggle(["kernels", "push", "-p", str(KERNEL_DIR)])
    ref = meta["id"]
    conn = db.connect()
    try:
        # a re-push of the same kernel replaces the previous version on
        # Kaggle — retire any still-open rows for this ref so the poller
        # only tracks the newest push
        conn.execute(
            "UPDATE cloud_runs SET status='superseded' WHERE kernel_ref=? AND"
            " status IN ('pushed','running')",
            (ref,),
        )
        conn.execute(
            "INSERT INTO cloud_runs (kernel_ref, config_path, status, created_at)"
            " VALUES (?,?,?,?)",
            (ref, str(config), "pushed", db.utcnow()),
        )
        conn.commit()
    finally:
        conn.close()
    return ref


def _set_status(ref: str, new_status: str) -> None:
    conn = db.connect()
    try:
        conn.execute(
            "UPDATE cloud_runs SET status=? WHERE id = (SELECT MAX(id) FROM"
            " cloud_runs WHERE kernel_ref=?)",
            (new_status, ref),
        )
        conn.commit()
    finally:
        conn.close()


def poll_once() -> list[str]:
    """Advance every open cloud run one step; auto-merge completed ones.

    Called by the API server's background poller and usable from the CLI.
    Returns human-readable events (empty = nothing changed).
    """
    events: list[str] = []
    conn = db.connect()
    try:
        rows = [dict(r) for r in conn.execute(
            "SELECT * FROM cloud_runs WHERE status IN ('pushed','running')"
            " ORDER BY id DESC"
        ).fetchall()]
    finally:
        conn.close()
    seen: set[str] = set()
    for row in rows:
        ref = row["kernel_ref"]
        if ref in seen:
            continue
        seen.add(ref)
        try:
            s = status(ref)
        except CloudError:
            continue
        if s == "running" and row["status"] != "running":
            _set_status(ref, "running")
            events.append(f"training running on Kaggle: {ref}")
        elif s == "complete":
            try:
                new_ids = pull(ref)
                events.append(
                    f"cloud training complete — merged as train run(s) "
                    f"{', '.join(f'#{i}' for i in new_ids)}"
                )
            except Exception as exc:
                # transient (network) failures must NOT end the run's story —
                # leave the row open so the next poll retries the pull
                events.append(f"merge attempt failed, will retry: {exc}")
        elif s in ("error", "cancelacknowledged"):
            _set_status(ref, "error")
            events.append(f"cloud training failed on Kaggle: {ref}")
    return events


def status(ref: str) -> str:
    out = _kaggle(["kernels", "status", ref])
    match = re.search(r'status "(?:\w+\.)?(\w+)"', out)
    return (match.group(1) if match else out.strip()).lower()


def pull(ref: str) -> list[int]:
    """Download finished kernel output and merge artifacts into the lab."""
    from . import artifacts

    dest = OUTPUT_DIR / ref.split("/")[-1]
    dest.mkdir(parents=True, exist_ok=True)
    _kaggle(["kernels", "output", ref, "-p", str(dest)])
    zips = list(dest.glob("*.zip"))
    source = zips[0] if zips else dest
    new_ids = artifacts.merge_artifacts(source)
    conn = db.connect()
    try:
        conn.execute(
            "UPDATE cloud_runs SET status='merged', pulled_at=? WHERE kernel_ref=?",
            (db.utcnow(), ref),
        )
        conn.commit()
    finally:
        conn.close()
    return new_ids


def list_runs() -> list[dict]:
    conn = db.connect()
    try:
        rows = [dict(r) for r in conn.execute(
            "SELECT * FROM cloud_runs ORDER BY id DESC"
        ).fetchall()]
    finally:
        conn.close()
    return rows
