"""Cloud training on Kaggle's free GPUs, driven entirely from nanolab.

`nanolab train --cloud <config>` pushes a script kernel that clones this
repo, trains with `--resume`, runs the held-out exam, and leaves
adapters + the db as kernel output. `nanolab cloud pull` downloads that
output and merges it into the local lab. The user never opens a notebook.

Requires a one-time Kaggle setup: phone-verified account + API token at
~/.kaggle/kaggle.json. Kaggle constraint worth knowing: kernel logs and
output become available when the run FINISHES — status is live, logs are
not.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

from . import db

REPO_URL = "https://github.com/khwahish1509/RLPost.git"
KERNEL_DIR = Path(".cache") / "kaggle-kernel"
OUTPUT_DIR = Path(".cache") / "kaggle-output"


class CloudError(RuntimeError):
    pass


def _kaggle(args: list[str]) -> str:
    if not (Path.home() / ".kaggle" / "kaggle.json").exists():
        raise CloudError(
            "Kaggle API token missing. One-time setup: kaggle.com/settings → "
            "Create New Token → save as ~/.kaggle/kaggle.json (chmod 600). "
            "GPU kernels also need a phone-verified account."
        )
    proc = subprocess.run(["kaggle", *args], capture_output=True, text=True)
    if proc.returncode != 0:
        raise CloudError((proc.stderr or proc.stdout).strip()[-400:])
    return proc.stdout


def _username() -> str:
    return json.loads((Path.home() / ".kaggle" / "kaggle.json").read_text())["username"]


def kernel_slug(config_path: str | Path) -> str:
    stem = re.sub(r"[^a-z0-9-]+", "-", Path(config_path).stem.lower()).strip("-")
    return f"nanolab-train-{stem}"[:50]


def build_kernel_script(config_path: str | Path) -> str:
    return f'''"""nanolab cloud training kernel — generated by `nanolab train --cloud`."""
import os, subprocess, sys

def sh(cmd):
    print("$", cmd, flush=True)
    subprocess.run(cmd, shell=True, check=True)

sh("git clone --depth 1 {REPO_URL} nanolab")
os.chdir("nanolab")
sh(f"{{sys.executable}} -m pip install -q -e . peft prime")
sh("prime env install primeintellect/gsm8k --with pip")
sh(f"{{sys.executable}} -m nanolab.cli train {config_path} --resume")
sh(f"{{sys.executable}} scripts/compare_adapter.py")
sh("zip -qr /kaggle/working/nanolab-artifacts.zip adapters results/nanolab.db")
print("CLOUD RUN COMPLETE", flush=True)
'''


def build_kernel_metadata(config_path: str | Path) -> dict:
    slug = kernel_slug(config_path)
    return {
        "id": f"{_username()}/{slug}",
        "title": slug,
        "code_file": "kernel_script.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": "true",
        "enable_gpu": "true",
        "enable_internet": "true",
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }


def push(config_path: str | Path) -> str:
    config = Path(config_path)
    if not config.is_file():
        raise CloudError(f"Config not found: {config}")
    KERNEL_DIR.mkdir(parents=True, exist_ok=True)
    meta = build_kernel_metadata(config)
    (KERNEL_DIR / "kernel-metadata.json").write_text(json.dumps(meta, indent=2))
    (KERNEL_DIR / "kernel_script.py").write_text(build_kernel_script(config))
    out = _kaggle(["kernels", "push", "-p", str(KERNEL_DIR)])
    ref = meta["id"]
    conn = db.connect()
    try:
        conn.execute(
            "INSERT INTO cloud_runs (kernel_ref, config_path, status, created_at)"
            " VALUES (?,?,?,?)",
            (ref, str(config), "pushed", db.utcnow()),
        )
        conn.commit()
    finally:
        conn.close()
    return ref


def status(ref: str) -> str:
    out = _kaggle(["kernels", "status", ref])
    match = re.search(r'status "?(\w+)"?', out)
    return (match.group(1) if match else out.strip()).lower()


def pull(ref: str) -> list[int]:
    """Download finished kernel output and merge artifacts into the lab."""
    from . import artifacts

    dest = OUTPUT_DIR / ref.split("/")[-1]
    dest.mkdir(parents=True, exist_ok=True)
    _kaggle(["kernels", "output", ref, "-p", str(dest)])
    zips = list(dest.glob("*.zip"))
    source = zips[0] if zips else dest
    new_ids = artifacts.merge_artifacts(source)
    conn = db.connect()
    try:
        conn.execute(
            "UPDATE cloud_runs SET status='merged', pulled_at=? WHERE kernel_ref=?",
            (db.utcnow(), ref),
        )
        conn.commit()
    finally:
        conn.close()
    return new_ids


def list_runs() -> list[dict]:
    conn = db.connect()
    try:
        rows = [dict(r) for r in conn.execute(
            "SELECT * FROM cloud_runs ORDER BY id DESC"
        ).fetchall()]
    finally:
        conn.close()
    return rows
